config/routes.rb
Rails.application.routes.draw do
	root 'generate_url#index'
	resources :generate_url
	resources :stats,only: [:index]
	get '/:shorten_url', :to => 'generate_url#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.get_env_variables(key)
  	Rails.application.credentials[Rails.env.to_sym][key.to_sym]
  end
end

app/models/url.rb
class Url < ApplicationRecord
	has_many :visit_histories,dependent: :destroy
	before_create :generate_shorten_url
  scope :expired_urls , -> { where("created_at < ?",1.month.ago)}

	def generate_shorten_url
    self.shorten = loop do
      random_token = SecureRandom.alphanumeric(5)
      break random_token unless Url.exists?(shorten: random_token)
    end
  end

  def shorten_url
  	ApplicationRecord.get_env_variables("url") + self.shorten
  end

  def top_countries
    top_countries = visit_histories.order("count(country) DESC").group("country")
    unless top_countries.blank?
      top_countries.limit(3).pluck(:country)
    end
  end
end

app/models/visit_history.rb
class VisitHistory < ApplicationRecord
	DEFAULT_COUNTRY = "US"
	belongs_to :url
	
	class << self
		def create_analysis(ip,country,url_obj)
			country ||= DEFAULT_COUNTRY
			VisitHistory.create(ip_address: ip, country: country,url_id: url_obj.id)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/generate_url_controller.rb
class GenerateUrlController < ApplicationController

	def index
	end

	def create
		@url = Url.find_or_create_by(original: params[:url])
	end

	def show
		@url = Url.find_by_shorten(params[:shorten_url])
		if @url
			VisitHistory.create_analysis(request.location.ip,request.location.country,@url)
			redirect_to @url.original
		end
	end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

	def index
		@urls = Url.includes(:visit_histories)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def comma_seperated(values)
		values.reject(&:blank?).join(",")
	end
end

app/views/generate_url/create.js.erb
str = "Here's your short URL! \n\n"
str += '<%= link_to @url.shorten_url, @url.shorten_url  %>'
jQuery("[data-id='show-url']").html(str);

app/views/generate_url/index.html.erb
<%= form_with url: generate_url_index_path do |form| %>
  <%= form.text_field :url %>
  <%= form.submit "Shorten" %>
<% end %>

<p data-id="show-url">	
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/index.html.erb
<% @urls.each do |url| %>
	<h2><%= link_to url.original,url.original %></h2>
	<h4><%= link_to url.shorten_url,url.shorten_url %></h4>
	<h6>Total Clicks: <%= url.visit_histories.count %></h6>
	<h6>Top Countries: <%= comma_seperated(url.top_countries) %></h6>
	<hr/>
<% end %>